# General Jekyll Config
author: Ken Davidson
email: ken.j.davidson@live.ca
title: Rouge Highlight Base16 SCSS
description: >
  Rouge highlight theme support based on scss and base16.

baseurl: "/rouge-base16-scss"
url: # the base hostname & protocol for your site
git_address: https://github.com/rouge-base16-scss
git_address: https://github.com/rouge-base16-scss/docs

bootwatch: paper
markdown: kramdown
highlighter: rouge

remote_theme: kenjdavidson/jekyll-doc-theme

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
excerpt_separator: <!--more-->

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true